#ifndef CONFIG_H
#define CONFIG_H

#define DEFAULT_MIN_MOISTURE 35 
#define DEFAULT_MAX_MOISTURE 65 
#define DEFAULT_MAX_WATER_SEC 30 
#define DEFAULT_SENSOR_INTERVAL_SEC 5 
#define MANUAL_WATER_SEC 10 

#endif